image: "python:3.10"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Unit Tests

unittest_unit:
  stage: Unit Tests
  script:
  - python -m unittest discover test/unit